[general]
description = "ノミナルケース"
step_max = 500

[model]
cohere = 0.025
height = 100
match = 0.04
population = 30
separate = 0.25
separation = 2
speed = 1
vision = 15
width = 100

[movie]
dpi = 200
interval = 50

[display]
interval = 3
